version: '3.8'

services:
  mysql:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork
  datadog:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=4426ed4fa4fa53079e94e7e6c1424ba5
      - DD_APM_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    networks:
      - mynetwork
  # rock-paper-scissors-service:
  #   build:
  #     context: ./rock-paper-scissors-service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mysql
  #     - datadog
  #   networks:
  #     - mynetwork

networks:
  mynetwork:
    driver: bridge
volumes:
  mysql-data:
