logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO

spring:
  redis:
    host: redis
    port: 6379
  datasource:
    url: jdbc:mysql://mysql:3306/rock_paper_scissors_game?allowPublicKeyRetrieval=true
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: person-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        temp:
          use_jdbc_metadata_defaults: false
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1,expireAfterWrite=600s
  sql:
    init:
      mode: never

datadog:
  agent:
    host: localhost
    port: 8125

server:
  port: 8080

game:
  server_player_id: 1
